
package com.storageservice.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ExternalApiModel", targetNamespace = "http://ws.storageservice.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ExternalApiModel {


    /**
     * 
     * @param personId
     * @return
     *     returns com.storageservice.ws.Bmi
     */
    @WebMethod
    @WebResult(name = "bmi", targetNamespace = "")
    @RequestWrapper(localName = "getbmi", targetNamespace = "http://ws.storageservice.com/", className = "com.storageservice.ws.Getbmi")
    @ResponseWrapper(localName = "getbmiResponse", targetNamespace = "http://ws.storageservice.com/", className = "com.storageservice.ws.GetbmiResponse")
    @Action(input = "http://ws.storageservice.com/ExternalApiModel/getbmiRequest", output = "http://ws.storageservice.com/ExternalApiModel/getbmiResponse")
    public Bmi getbmi(
        @WebParam(name = "personId", targetNamespace = "")
        long personId);

    /**
     * 
     * @param personId
     * @return
     *     returns com.storageservice.ws.Person
     */
    @WebMethod
    @WebResult(name = "bmi", targetNamespace = "")
    @RequestWrapper(localName = "getPersonInformation", targetNamespace = "http://ws.storageservice.com/", className = "com.storageservice.ws.GetPersonInformation")
    @ResponseWrapper(localName = "getPersonInformationResponse", targetNamespace = "http://ws.storageservice.com/", className = "com.storageservice.ws.GetPersonInformationResponse")
    @Action(input = "http://ws.storageservice.com/ExternalApiModel/getPersonInformationRequest", output = "http://ws.storageservice.com/ExternalApiModel/getPersonInformationResponse")
    public Person getPersonInformation(
        @WebParam(name = "personId", targetNamespace = "")
        long personId);

    /**
     * 
     * @param personId
     * @return
     *     returns com.storageservice.ws.Person
     */
    @WebMethod
    @WebResult(name = "person", targetNamespace = "")
    @RequestWrapper(localName = "readPerson", targetNamespace = "http://ws.storageservice.com/", className = "com.storageservice.ws.ReadPerson")
    @ResponseWrapper(localName = "readPersonResponse", targetNamespace = "http://ws.storageservice.com/", className = "com.storageservice.ws.ReadPersonResponse")
    @Action(input = "http://ws.storageservice.com/ExternalApiModel/readPersonRequest", output = "http://ws.storageservice.com/ExternalApiModel/readPersonResponse")
    public Person readPerson(
        @WebParam(name = "personId", targetNamespace = "")
        long personId);

    /**
     * 
     * @return
     *     returns java.util.List<com.storageservice.ws.Person>
     */
    @WebMethod
    @WebResult(name = "people", targetNamespace = "")
    @RequestWrapper(localName = "readPersonList", targetNamespace = "http://ws.storageservice.com/", className = "com.storageservice.ws.ReadPersonList")
    @ResponseWrapper(localName = "readPersonListResponse", targetNamespace = "http://ws.storageservice.com/", className = "com.storageservice.ws.ReadPersonListResponse")
    @Action(input = "http://ws.storageservice.com/ExternalApiModel/readPersonListRequest", output = "http://ws.storageservice.com/ExternalApiModel/readPersonListResponse")
    public List<Person> readPersonList();

    /**
     * 
     * @param lng
     * @param lat
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "weather", targetNamespace = "")
    @RequestWrapper(localName = "getWeatherByLatLng", targetNamespace = "http://ws.storageservice.com/", className = "com.storageservice.ws.GetWeatherByLatLng")
    @ResponseWrapper(localName = "getWeatherByLatLngResponse", targetNamespace = "http://ws.storageservice.com/", className = "com.storageservice.ws.GetWeatherByLatLngResponse")
    @Action(input = "http://ws.storageservice.com/ExternalApiModel/getWeatherByLatLngRequest", output = "http://ws.storageservice.com/ExternalApiModel/getWeatherByLatLngResponse")
    public String getWeatherByLatLng(
        @WebParam(name = "lat", targetNamespace = "")
        String lat,
        @WebParam(name = "lng", targetNamespace = "")
        String lng);

}
